platform :ios, '12.0'

inhibit_all_warnings!
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

target 'Torrentino' do
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Differ'
  pod 'LNZTreeView'
end

post_install do |installer|
  pods_project = installer.pods_project

  pods_project.build_configurations.each do |config|
    config.build_settings['SWIFT_VERSION'] = '5.0'
    config.build_settings['ONLY_ACTIVE_ARCH'] = config.name == 'Debug' ? 'YES' : 'wholemodule'
    config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = config.name == 'Debug' ? '-Onone' : '-O'
  end

  pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IOS_DEPLOYMENT_TARGET'] = '12.0'
      ['SWIFT_VERSION', 'ONLY_ACTIVE_ARCH', 'SWIFT_OPTIMIZATION_LEVEL', 'SWIFT_COMPILATION_MODE'].each do |option| 
        config.build_settings.delete(option) 
      end
    end
  end
end
